### PR TITLE
Update: bpf cmd format

### LINKED ISSUE #203: Update rule "BPF Program Not Profiled" with new bpf cmd format
Update rule "BPF Program Not Profiled" with new bpf cmd format based on changes implemented in https://github.com/falcosecurity/libs/pull/1545

### PR DESCRIPTION
**Pull request by Rohith-Raju**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area rules

**Proposed rule [maturity level](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md#maturity-levels)**

/area maturity-sandbox

**What this PR does / why we need it**: 

This PR updates new bpf cmd format based on changes implemented in https://github.com/falcosecurity/libs/pull/1545

**Which issue(s) this PR fixes**: 

Fixes #203 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by incertum** [comment]
Thanks @Rohith-Raju ❤️ 

/hold for a while since we won't have that until libs 0.15.0 and the next Falco release will use libs 0.14.x

Anticipate to hold it until at least February / March.

**Comment by Rohith-Raju** [comment]
Sounds good!! @incertum

**Comment by leogr** [comment]
> Anticipate to hold it until at least February / March.

Reminder: we will also need to update `required_engine_version` accordingly.

**Comment by incertum** [comment]
@Rohith-Raju we finally have the libs changes in Falco master, please bump the `required_engine_version` to 0.35.0 in the rules file you touched, see https://github.com/falcosecurity/falco/blob/master/userspace/engine/falco_engine_version.h#L23 plus a rebase is needed. Thanks!

**Review by incertum — APPROVED** [review]
/approve

@leogr I let you decide when to merge via unholding this. Thanks. 
From my perspective we are good to go since we recently made it more clear that the main branch has the latest development.

**Review by leogr — APPROVED** [review]
:+1: 

/hold cancel

Note: This change makes this ruleset compatible with Falco 0.38 and up only.

**Pull request merged**
