### PR TITLE
vote: Adding @darryk10 to rules approvers

### PR DESCRIPTION
**Pull request by darryk10**
**What type of PR is this?**
After more than a year as a reviewer in the falcosecurity/rules repo and more than 3 years as a contributor in the Falco community, I want to propose myself as a rule approver.

> Uncomment one (or more) `/kind <>` lines:

> /kind feature

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area rules

> /area registry

> /area build

> /area documentation

**Proposed rule [maturity level](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md#maturity-levels)**

> Uncomment one (or more) `/area <>` lines (only for PRs that add or modify rules):

> /area maturity-stable

> /area maturity-incubating

> /area maturity-sandbox

> /area maturity-deprecated

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leogr** [comment]
Big +1 from me! 

/hold until we reach the majority or a week has passed 

cc @falcosecurity/rules-maintainers

**Comment by LucaGuerra** [comment]
+1 , thank you @darryk10 !

**Comment by leogr** [comment]
PS this PR triggered a bug in the CI that validates rules. I will dig into it. It's unrelated to this PR, so please ignore it.

**Review by Kaizhe — APPROVED** [review]
well deserved!

**Comment by FedeDP** [comment]
+1 from me! Welcome!!

**Review by leogr — APPROVED** [review]
With 5 binding votes in favor and nobody against [Majory vote](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#majority-vote) has passed!

@darryk10 welcome onboard! :clap: 

/hold cancel

**Pull request merged**
