### PR TITLE
fix(rules): fix ptrace attach and injection rule

### PR DESCRIPTION
**Pull request by loresuso**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area rules

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:
This rule was built on top of a bug, see https://github.com/falcosecurity/libs/pull/970
Once that one will be merged and Falco can use it, we should merge this PR as well.
For the same reason, some other rules stopped working, like https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L2950 because the flag was not retrieved as string anymore. This makes me think we need a better CI :) 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by darryk10** [comment]
hi @loresuso, thanks for the that and the rule seems more accurate then before so that's great.
Reviewing the PR isn't clear the other rules that stopped working since the link point to a macro https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L2950. Can you clarify that pls?
Thanks

**Comment by darryk10** [comment]
noted! thanks.
this LGTM.

**Review by darryk10 — DISMISSED** [review]

**Comment by loresuso** [comment]
I have added other commits to:
- make the "Packet socket created in container" work again. This commit can be cherry picked if we want to release a patched ruleset
- revert the commit before
- let the rule use `contains` operator is better because of the way things are extracted. This is what we will keep after the fix got it.

**Pull request merged**
