### PR TITLE
vote: update(OWNERS): add loresuso to approvers

### PR DESCRIPTION
**Pull request by loresuso**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind feature

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

 /area rules

> /area registry

> /area build

> /area documentation

**Proposed rule [maturity level](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md#maturity-levels)**

> Uncomment one (or more) `/area <>` lines (only for PRs that add or modify rules):

> /area maturity-stable

> /area maturity-incubating

> /area maturity-sandbox

> /area maturity-deprecated

**What this PR does / why we need it**:

Hello everyone, 
I would like to propose myself as a Falco Rules maintainer. I've been involved in the project for two years and a half now, consistently helping review rules, proposing new ones, implementing some new fields for better detection, working on the CI of this repo for shipping rules as OCI artifacts, and also helping with the transition to a semver engine version. I would love to continue contributing as a maintainer of this repo :)

cc @falcosecurity/rules-maintainers to start the voting process!

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by incertum** [comment]
Big +1 :heart: finally Lorenzo -- a pleasure to have you on board as approver :wink:

**Comment by FedeDP** [comment]
+1 from me! Welcome on board :ship:

**Comment by Andreagit97** [comment]
+1 from me!

**Comment by LucaGuerra** [comment]
Big +1 🚀

**Comment by darryk10** [comment]
big +1!!

**Comment by leogr** [comment]
With a lot of votes in favor and nobody against [Majory vote](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#majority-vote) has passed!

/unhold 

:partying_face:

**Review by leogr — APPROVED** [review]

**Comment by loresuso** [comment]
Thank you all! 🎉

**Pull request merged**
