### PR TITLE
fix: trim spaces for required_engine_version and use atoi to parse in…

### LINKED ISSUE #225: Invalid engine_version_semver key in latest rules package
**Describe the bug**

The newly released package for the Falco rules contains a semver version of 0.0.0
```
falcoctl artifact config falco-rules | jq 
{
  "name": "falco-rules",
  "version": "3.0.0",
  "requirements": [
    {
      "name": "engine_version_semver",
      "version": "0.0.0"
    }
  ]
}
```

Together with @leogr we spotted the bug. I'll open a PR soon to fix it.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/rules/pull/226
- [x] Republish artifacts
```

### PR DESCRIPTION
**Pull request by loresuso**
…teger version in case

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind feature

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area rules

/area registry

> /area build

> /area documentation

**Proposed rule [maturity level](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md#maturity-levels)**

> Uncomment one (or more) `/area <>` lines (only for PRs that add or modify rules):

> /area maturity-stable

> /area maturity-incubating

> /area maturity-sandbox

> /area maturity-deprecated

**What this PR does / why we need it**:

see related issue

**Which issue(s) this PR fixes**:

Fixes #225

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by loresuso** [comment]
Same problem is present on plugins repo. When this is ok, I'll bring the changes also there

**Comment by loresuso** [comment]
cc @leogr

**Review by jasondellaluce — COMMENTED** [review]
LGTM

**Comment by leogr** [comment]
cc @lg @alacuku

**Review by leogr — APPROVED** [review]

**Pull request merged**
