### PR TITLE
new(rules): Change namespace privileges via unshare

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area rules

> /area registry

> /area build

> /area documentation

**Proposed rule [maturity level](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md#maturity-levels)**

> Uncomment one (or more) `/area <>` lines (only for PRs that add or modify rules):

> /area maturity-stable

/area maturity-incubating

> /area maturity-sandbox

> /area maturity-deprecated

**What this PR does / why we need it**:

See `desc` and also part of modernizing Falco rules https://github.com/falcosecurity/rules/issues/138.
CC @darryk10 @Andreagit97 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by darryk10 — APPROVED** [review]
Hi @incertum, the use case is awesome and checking the rule it seems pretty accurate with low FPs. 
LGTM

**Review by LucaGuerra — APPROVED** [review]

**Review by darryk10 — APPROVED** [review]

**Review by Andreagit97 — APPROVED** [review]
thanks for this!
/approve

**Comment by Andreagit97** [comment]
/hold
Why the CI is failing?

**Comment by incertum** [comment]
Because the memfd + exec rule made it already incompatible with 0.35.

**Pull request merged**
