### PR TITLE
update(rules): bump engine version to Falco 0.37.0 engine version

### PR DESCRIPTION
**Pull request by Andreagit97**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area rules

**Proposed rule [maturity level](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md#maturity-levels)**

/area maturity-stable

/area maturity-incubating

/area maturity-sandbox

/area maturity-deprecated

**What this PR does / why we need it**:

This bumps the engine version to Falco 0.37.0 engine version

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Andreagit97** [comment]
/hold
Not sure if we need something else please double-check

**Review by leogr — DISMISSED** [review]
:+1:

**Comment by leogr** [comment]
@Andreagit97 

This change makes the rulesets incompatible with Falco 0.36 (that's fine anyway). Thus, this requires:
- to update https://github.com/falcosecurity/rules/blob/main/.github/FALCO_VERSIONS with the supported versions of Falco (ie. master and 0.37 once released)
- to bump the ruleset major number

Note:
This doc https://github.com/falcosecurity/rules/blob/main/RELEASE.md#versioning-a-ruleset states that it would be enough to just bump the minor version. I don't recall why, but I don't think bumping just the minor is enough. Perhaps we have to update the release doc. cc @LucaGuerra @jasondellaluce

**Review by incertum — COMMENTED** [review]
LGTM from my side!

**Comment by Andreagit97** [comment]
> to update https://github.com/falcosecurity/rules/blob/main/.github/FALCO_VERSIONS with the supported versions of Falco (ie. master and 0.37 once released)

Done, we will need to add Falco 0.37.0 when released

/unhold

Could you please re-approve?

**Review by leogr — APPROVED** [review]

**Pull request merged**
