### PR TITLE
new(rules): BPF Program Not Profiled

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind feature

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area rules

> /area registry

> /area build

> /area documentation

**Proposed rule [maturity level](https://github.com/falcosecurity/rules/blob/main/CONTRIBUTING.md#maturity-levels)**

> Uncomment one (or more) `/area <>` lines (only for PRs that add or modify rules):

> /area maturity-stable

> /area maturity-incubating

/area maturity-sandbox

> /area maturity-deprecated

**What this PR does / why we need it**:

See rules `desc`.

@Andreagit97 @darryk10 @loresuso thanks!

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by incertum** [comment]
> just to keep in mind there might be some other projects using bpf which might need to be whitelist but this is a great starting point. thanks LGTM

Agreed we could over time add some of the most popular programs in Kubernetes settings at least. Meanwhile, it's stated that it requires customization.

**Comment by incertum** [comment]
Captured some future logging improvements here https://github.com/falcosecurity/libs/issues/1343 as discussed.

**Comment by incertum** [comment]
Just noticed for bpf syscall it would be `evt.res_or_fd` and not `evt.res` @Andreagit97 plz confirm.

Also should count as contribution to our modernization effort tracked here https://github.com/falcosecurity/rules/issues/138.

**Review by Andreagit97 — APPROVED** [review]
/approve

**Pull request merged**
