### PR TITLE
Add artifact signature information to the generated index

### LINKED ISSUE #100: Add Signature section to index files generated by GHA
**Motivation**

We have support for signatures in rules and plugins but we need to add this info to the index so that the signature can be verified, see example: https://github.com/falcosecurity/falcoctl/pull/305

### PR DESCRIPTION
**Pull request by maxgio92**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area registry
/area build

**What this PR does / why we need it**:

This PR is needed to provide required information for consumers in order to verify OCI signatures of rules officially distributed as OCI artifacts.

The `registry.yaml` index is consumed by current CI to generate the general Falco artifacts index https://github.com/falcosecurity/falcoctl/blob/gh-pages/index.yaml, which can be further consumed by [falcoctl](https://github.com/falcosecurity/falcoctl) to verify artifacts (i.e. rules) signatures.

**Which issue(s) this PR fixes**:

Fixes #100 

**Special notes for your reviewer**:

Only one signin implementation is currently supported, which is based on cosign. When signatures are generated by cosign in keyless mode, can provide the OIDC issuer and certificate identity (see https://github.com/falcosecurity/falcoctl/pull/305).
 
Furthermore, this PR adds black box and white box unit tests.

The same feature should be applied to the registry tool of the [plugins](https://github.com/falcosecurity/plugins) (https://github.com/falcosecurity/plugins/pull/312).

### CODE REVIEW

**Comment by maxgio92** [comment]
I'd wait for #64 to merge this.
/hold

**Comment by incertum** [comment]
@maxgio92 could we get a rebase? Thanks. Is this ready to be reviewed and merged?
CC @LucaGuerra

**Comment by LucaGuerra** [comment]
I've identified and fixed a bug in falcoctl that prevented this info from being parsed correctly. Just want to make sure that all is good before merging this one because it'll affect Falco 0.36.0 users :) My plan is to finish this work within a week.

**Comment by maxgio92** [comment]
Hey @incertum @LucaGuerra, I've just rebased on top of main and with the occasion I upgraded falcoctl dependency to v0.6.0

**Review by LucaGuerra — APPROVED** [review]
Thank you for the update and rebase! I have tested this with the current registries and indexes and it works as we expect :tada: 

Now, after the Go update in test-infra is complete we'll be able to deploy this.

**Pull request merged**
