### PR TITLE
adds Falco rule to detect discovery of all peripheral devices

### PR DESCRIPTION
**Pull request by ashutoshmore658**
Signed-off-by: ashutoshmore658 ashutoshmore658@gmail.com (CloudDefense.AI)

**What type of PR is this?**

> /kind feature

**Any specific area of the project related to this PR?**

> /area rules

**Special notes for your reviewer**:
This PR detects the enumeration of all peripheral devices connected to the system. The rule addresses detection of activity related to getting information about all the peripheral devices connected to a system. Since this type of activity can lead to sever threat for Intrusion into the system.

### CODE REVIEW

**Review by loresuso — APPROVED** [review]
LGTM! A suggestion I have is to put a lower priority to this rule, NOTICE should be enough

**Review by loresuso — COMMENTED** [review]
Furthermore, all commits should follow the conventional commit format https://www.conventionalcommits.org/en/v1.0.0/
Could you please stick to it also in the other PRs? :)

**Comment by incertum** [comment]
@ashutoshmore658 could we get a rebase, thanks!

**Pull request closed without merging**
